Improvement/placement landinage page banner
scania-digital-design-system/sdds-website pull request #202
Opened 2020-12-22 12:50 UTC by mmexvr

**Describe pull-request**  
_Describe what the pull-request is about_

- Fixing templates
- Fixing reference to old corporate-ui
- Updated readme
- Updated templates
- Landing page had wrong columns on grid(Might need to remove the fluid talk with niklas regarding using fluid or not)
- Caption color
- Package.json

**Solving issue**  
_Add which issue this pull-request solves by adding # plus the number of the issue (for example #123)_
Fixes: #201 
Fixes: #165 
Also, but needs to discusses : #182

**How to test**  
_Add description how to test if possible_
- Read the readme.md
- Read issues
- Look at site with image caption, correct color
- Look at the banner in bottom, related with #182 
- Packages json

2021-01-04 07:41 UTC, helloimela requested changes

2021-01-04 07:41 UTC, helloimela commented on README.md
> +This is used to be able to run the local version on your compunter toghether with the website. To find out more about the SDDS component and themes packages please visit [scania-digital-design-system
Typo: computer

2021-01-04 12:27 UTC, helloimela commented on README.md
>  For more information how to contribute [Digitaldesign.scania.com/getting-started/](https://digitaldesign.scania.com/getting-started/development)
How to get started using it and how to contribute is two different thing.
- Under this title, can change the sentence to: Check the documentation in [link]
- Can create a separate section for "How to contribute" and it should link to https://github.com/scania-digital-design-system/sdds/blob/master/CONTRIBUTING.md

2021-01-07 13:43 UTC, mmexvr commented on README.md
>  For more information how to contribute [Digitaldesign.scania.com/getting-started/](https://digitaldesign.scania.com/getting-started/development)
Should probably link also to the contribution page

2021-01-08 07:33 UTC, helloimela approved these changes

2021-01-12 13:30 UTC, helloimela approved these changes

2021-01-13 12:07 UTC, niklasros approved these changes

2021-01-13 12:37 UTC, helloimela approved these changes
Great job!

2021-01-13 12:38 UTC, merged