Improvement/cards addition
scania-digital-design-system/sdds-website pull request #252
Opened 2021-04-26 15:39 UTC by iths-jonathan-engman

**Describe pull-request**  
- Replaced the old cards code to the sdds card component

**Solving issue**  
_Add which issue this pull-request solves by adding # plus the number of the issue (for example #123)_
Fixes: #251 

**How to test**  
- cd sdds-website
- npm start

**Screenshots**  
![image](https://user-images.githubusercontent.com/54362354/116110519-0e5a7500-a6b6-11eb-9c0f-6d9cf4588f89.png)

**Additional context**  
- Might need addition to the component regarding downloadsize, showing in img

2021-04-29 14:12 UTC, vichtertz reviewed
Looks good! 
We just defined specific rules for the responsiveness:
- The cards should not exceed 8 columns width
- The cards width takes the same amount of columns on all device sizes. It only becomes full-width on mobile.

2021-05-03 13:15 UTC, helloimela commented
It's good that you added rotate to the arrow for external & internal link, I would also do the same. But in this case, the svg arrow looks a bit pixelated when it is being rotated. Not sure if you see same things @mmexvr 

![image](https://user-images.githubusercontent.com/1199101/116880211-06ed1b80-ac22-11eb-8265-333e78699980.png)

Compared to the arrow when I export the SVG directly from figma (diagonal arrow) exported from SDDS UI > Landing Page > Card with big image. 

![image](https://user-images.githubusercontent.com/1199101/116880325-26844400-ac22-11eb-8af5-8fb6f5befcb7.png)

It's very subtle, but maybe we can use a separate SVG for externalLink card for the arrow? (and not rotate internalLink arrow).
Any comments @mmexvr ?

2021-05-03 13:17 UTC, helloimela commented
It seems like the diagonal arrow in Figma has a longer "tail" than the internalLink arrow being rotated

2021-05-03 13:54 UTC, helloimela requested changes
Merge main to this branch first, it is far from the latest main branch!

2021-05-04 07:12 UTC, mmexvr commented on src/app/components/card/card.component.scss
> +      margin-bottom: 0px;
I think margin:0 should either follow the global pattern or we add in the component. Otherwise we will have two different cards, one with margin: 0 and one without. It is a bit weird if we don't follow our own cards

2021-05-04 07:13 UTC, mmexvr commented
> Any comments @mmexvr ?

Yeah, I think maybe it is better to use the angled arrow then instead of rotating

2021-05-04 07:14 UTC, mmexvr commented on src/app/components/card/card.component.scss
> +      margin-bottom: 0px;
Same with headline color, should this be added in our component. Otherwise what people use and what we use are different from the cards

2021-05-04 07:18 UTC, vichtertz commented on src/app/components/card/card.component.scss
> +      margin-bottom: 0px;
Regarding the headline color we wanted to wait before changing them to grey, as we will explore colored typography soon, if it sounds okay for you from a development perspective? Or just keep in mind that it might change again later on potentially.

2021-05-04 07:53 UTC, iths-jonathan-engman commented
![image](https://user-images.githubusercontent.com/54362354/116974493-83353c80-acbe-11eb-8c1a-bab0c2c08c96.png)
Separated linkInternal & linkExternal

2021-05-04 07:55 UTC, iths-jonathan-engman commented
![image](https://user-images.githubusercontent.com/54362354/116974697-c7c0d800-acbe-11eb-8ca6-61ff85972740.png)

2021-05-04 08:11 UTC, mmexvr commented on src/app/components/card/card.component.scss
> +      margin-bottom: 0px;
Ok good! Was just making sure :)

2021-05-04 12:20 UTC, vichtertz requested changes
The cards with images are good! 

All the other cards:

- Card width on screen-M should be changed to 4 columns (still full-width for a lot of them except from the Landing page)

- Put the card on 4 columns instead of 5 columns for screen-L, so we can have 2 cards next to each other actually, it's gonna look nicer.

![Screenshot 2021-05-04 at 11 36 05](https://user-images.githubusercontent.com/81550891/116985914-6a805300-accd-11eb-95d0-d609ef8beb4a.png)

- Still not sure why we use 15px padding to "compensate" the icon, can't it be 16px?

- The spacing between the text container and the arrow should be 32px in total (the text container should fit its content height, now the container is higher). Some of them are good but not for the ones having 2 lines of text. 

![Screenshot 2021-05-04 at 13 27 44 (2)](https://user-images.githubusercontent.com/81550891/116997433-141b1080-acdd-11eb-9b09-aad446f3a108.png)

2021-05-10 08:00 UTC, vichtertz approved these changes

2021-05-12 06:14 UTC, helloimela approved these changes

2021-05-12 08:30 UTC, mmexvr submitted a review, later dismissed

2021-05-12 13:55 UTC, vichtertz requested changes
Some cards still don't align on screen-M on the following pages:

- Getting started > Overview

<img width="821" alt="Screenshot 2021-05-12 at 15 40 06" src="https://user-images.githubusercontent.com/81550891/117984762-6640df00-b338-11eb-82ca-33a894f9b3a1.png">


-  Getting started > Design

<img width="877" alt="Screenshot 2021-05-12 at 15 38 40" src="https://user-images.githubusercontent.com/81550891/117984636-4a3d3d80-b338-11eb-925e-9630e7ebf906.png">

-  Getting started > Development

<img width="327" alt="Screenshot 2021-05-12 at 15 42 02" src="https://user-images.githubusercontent.com/81550891/117985166-c0da3b00-b338-11eb-88f6-7b0dd29d2659.png">

- Resources > Overview

<img width="321" alt="Screenshot 2021-05-12 at 15 44 56" src="https://user-images.githubusercontent.com/81550891/117985519-0f87d500-b339-11eb-80c1-9b4db514c560.png">

2021-05-24 08:08 UTC, vichtertz requested changes
- Still unaligned cards on Getting started > Overview between Screen-L and Screen-XL
![Screenshot 2021-05-24 at 10 00 10](https://user-images.githubusercontent.com/81550891/119316200-f48d5d00-bc76-11eb-9906-030e1c7ca936.png)

- Same for Getting Started > Design
![Screenshot 2021-05-24 at 10 05 26](https://user-images.githubusercontent.com/81550891/119316727-96ad4500-bc77-11eb-8a7c-ffeb4393f261.png)

2021-05-24 14:05 UTC, merged