Update content event
scania-digital-design-system/sdds-website pull request #293
Opened 2021-12-03 13:08 UTC by mmexvr

**Describe pull-request**  
_Describe what the pull-request is about_

**Solving issue**  
_Add which issue this pull-request solves by adding # plus the number of the issue (for example #123)_
Fixes: #

**How to test**  
_Add description how to test if possible_

**Screenshots**  
_If applicable, add screenshots to help explain_

**Additional context**  
_Add any other context about the pull-request here._

2021-12-03 13:23 UTC, charlottelorensson requested changes
- change images to pgn (button, form and card)

2021-12-03 15:21 UTC, mmexvr commented
Update the picture with png format

2021-12-07 13:44 UTC, mmexvr commented
- [x]  Link for powerpoint added @charlottelorensson 
- [ ] Change the last part of us being on site to being digital instead

2021-12-08 07:52 UTC, charlottelorensson approved these changes

2021-12-08 07:53 UTC, theJohnnyMe approved these changes

2021-12-08 07:54 UTC, merged