Bumped angular version from 8 to 12
scania-digital-design-system/sdds-website pull request #314
Opened 2022-02-15 10:47 UTC by albinscania

**Describe pull-request**  
Upgrade from angular version 8 to 12. Some minor refactoring to comply with the new version of typescript.

**Solving issue**  
Fixes: AB#1620

**How to test**  
Compare the ampliy version with the current production version and look for errors.

**Additional context**  
Added a small text file called "upgrade-notes.txt" that highlights the major steps taken. (copy pasted from CLI during update)

2022-02-15 12:17 UTC, gaonita approved these changes
Looks good to me. Awesome we finally updating! grrreat work! :)

2022-02-15 12:17 UTC, gaonita commented on src/app/app-routing.module.ts
> +};*/
duplicate comment?

2022-02-15 12:17 UTC, gaonita commented on tsconfig-es5.app.json
> +  },
^M? mysterious 😆

2022-02-15 12:17 UTC, gaonita commented on upgrade-notes.txt
> +
super! easy to follow about what's been done. thanks!

2022-02-15 12:43 UTC, areblk approved these changes
No visual or behavioral regressions noticed when comparing PR to https://digitaldesign.scania.com/

2022-02-16 08:56 UTC, theJohnnyMe requested changes
Looks awesome and works as well. There are only two comments that Gaon added, one for extra comment and another one that looks like a typo. Please check them and ping us after :)

2022-02-16 09:03 UTC, albinscania commented
Haha yeah, some auto merger-weirdness snuck in! Fixed now :)
Good find.

2022-02-16 09:36 UTC, theJohnnyMe approved these changes
Great! Thanks a lot Albin for sorting out this one. Go and "Squash and merge" it :)

2022-02-16 09:56 UTC, merged